src/Entity/RendezVous.php
<?php

namespace App\Entity;

use App\Repository\RendezVousRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RendezVousRepository::class)]
class RendezVous
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_rdv = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 50)]
    private ?string $status = null;

    #[ORM\ManyToOne(inversedBy: 'rendezVouses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Prestation $prestation = null;

    #[ORM\ManyToOne(inversedBy: 'rendezVouses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateRdv(): ?\DateTimeInterface
    {
        return $this->date_rdv;
    }

    public function setDateRdv(\DateTimeInterface $date_rdv): self
    {
        $this->date_rdv = $date_rdv;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getPrestation(): ?Prestation
    {
        return $this->prestation;
    }

    public function setPrestation(?Prestation $prestation): self
    {
        $this->prestation = $prestation;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/RendezVousType.php
<?php

namespace App\Form;

use App\Entity\Prestation;
use App\Entity\RendezVous;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class RendezVousType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_rdv', DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('name')
            ->add('status')
            ->add('prestation', EntityType::class, [
                'class' => Prestation::class,
                'choice_label' => 'name',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => RendezVous::class,
        ]);
    }
}

src/Controller/RendezVousController.php
<?php

namespace App\Controller;

use App\Entity\RendezVous;
use App\Form\RendezVousType;
use App\Repository\RendezVousRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin')]
class RendezVousController extends AbstractController
{
    #[Route('/rendez-vous', name: 'app_rendez_vous_index', methods: ['GET'])]
    public function index(RendezVousRepository $rendezVousRepository): Response
    {
        return $this->render('rendez_vous/index.html.twig', [
            'rendez_vous' => $rendezVousRepository->findAll(),
        ]);
    }

    #[Route('/rendez-vous/new', name: 'app_rendez_vous_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RendezVousRepository $rendezVousRepository): Response
    {
        $rendezVous = new RendezVous();
        $form = $this->createForm(RendezVousType::class, $rendezVous);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $rendezVous->setUser($this->getUser());// lier le rdv à un user
            if ($rendezVous->getUser() == $this->getUser()) {
            $rendezVousRepository->save($rendezVous, true);
            }
            return $this->redirectToRoute('app_rendez_vous_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('rendez_vous/new.html.twig', [
            'rendez_vous' => $rendezVous,
            'form' => $form,
        ]);
    }

    #[Route('/rendez-vous/{id}', name: 'app_rendez_vous_show', methods: ['GET'])]
    public function show(RendezVous $rendezVou): Response
    {
        return $this->render('rendez_vous/show.html.twig', [
            'rendez_vou' => $rendezVou,
        ]);
    }

    #[Route('/rendez-vous/{id}/edit', name: 'app_rendez_vous_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, RendezVous $rendezVou, RendezVousRepository $rendezVousRepository): Response
    {
        $form = $this->createForm(RendezVousType::class, $rendezVou);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $rendezVousRepository->save($rendezVou, true);

            return $this->redirectToRoute('app_rendez_vous_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('rendez_vous/edit.html.twig', [
            'rendez_vou' => $rendezVou,
            'form' => $form,
        ]);
    }

    #[Route('/rendez-vous/{id}', name: 'app_rendez_vous_delete', methods: ['POST'])]
    public function delete(Request $request, RendezVous $rendezVou, RendezVousRepository $rendezVousRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $rendezVou->getId(), $request->request->get('_token'))) {
            $rendezVousRepository->remove($rendezVou, true);
        }

        return $this->redirectToRoute('app_rendez_vous_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/rendez-vous/prise/validation/{id}', name: 'app_validation_rendez_vous', methods: 'GET')]
    public function validation(RendezVous $rendezVous, RendezVousRepository $rendezVousRepository): Response
    {
        if (!$rendezVous) {
            throw $this->createNotFoundException("ce rendez-vous n'existe pas.");
        }

        $rendezVous->setStatus("validé");
        $rendezVousRepository->save($rendezVous, true);

        $this->addFlash('success', "Le rendez-vous " . $rendezVous->getName() . " a été validé.");

        return $this->redirectToRoute('app_rendez_vous_index');
    }
}

templates/rendez_vous/_delete_form.html.twig
<form method="post" action="{{ path('app_rendez_vous_delete', {'id': rendez_vou.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rendez_vou.id) }}">
    <button class="btn">Delete</button>
</form>

templates/rendez_vous/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit RendezVous{% endblock %}

{% block body %}
    <h1>Edit RendezVous</h1>

    {{ include('rendez_vous/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_rendez_vous_index') }}">back to list</a>

    {{ include('rendez_vous/_delete_form.html.twig') }}
{% endblock %}

templates/rendez_vous/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}RendezVous index
{% endblock %}

{% block body %}
	<h1>RendezVous index</h1>

	{% include 'includes/_flashes.html.twig' %}

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Date_rdv</th>
				<th>Name</th>
				<th>Status</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for rendez_vous in rendez_vous %}
				<tr>
					<td>{{ rendez_vous.id }}</td>
					<td>{{ rendez_vous.dateRdv ? rendez_vous.dateRdv|date('Y-m-d') : '' }}</td>
					<td>{{ rendez_vous.name }}</td>
					<td>{{ rendez_vous.status }}</td>
					<td>
						{% if rendez_vous.status == "réservé" %}
							<a href="{{ path('app_rendez_vous_show', {'id': rendez_vous.id}) }}">show</a>
							<a href="{{ path('app_rendez_vous_edit', {'id': rendez_vous.id}) }}">edit</a>
							<a href="{{ path('app_validation_rendez_vous', {'id': rendez_vous.id}) }}">validate</a>

						{% else %}
							<a href="{{ path('app_rendez_vous_show', {'id': rendez_vous.id}) }}">show</a>
							<a href="{{ path('app_rendez_vous_edit', {'id': rendez_vous.id}) }}">edit</a>
						{% endif %}
					</td>
				</tr>
			</td>
		</tbody>
	</tr>
{% else %}
	<tr>
		<td colspan="5">no records found</td>
	</tr>
{% endfor %}</tbody></table><a href="{{ path('app_rendez_vous_new') }}">Create new</a>{% endblock %}

templates/rendez_vous/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New RendezVous{% endblock %}

{% block body %}
    <h1>Create new RendezVous</h1>

    {{ include('rendez_vous/_form.html.twig') }}

    <a href="{{ path('app_rendez_vous_index') }}">back to list</a>
{% endblock %}

templates/rendez_vous/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}RendezVous
{% endblock %}

{% block body %}
	<h1>Rendez-vous</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ rendez_vou.id }}</td>
			</tr>
			<tr>
				<th>Date_rdv</th>
				<td>{{ rendez_vou.dateRdv ? rendez_vou.dateRdv|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>Name</th>
				<td>{{ rendez_vou.name }}</td>
			</tr>
			<tr>
				<th>Status</th>
				<td>{{ rendez_vou.status }}</td>
			</tr>
		</tbody>
	</table>

	<a href="{{ path('app_rendez_vous_index') }}">back to list</a>

	<a href="{{ path('app_rendez_vous_edit', {'id': rendez_vou.id}) }}">edit</a>

	{{ include('rendez_vous/_delete_form.html.twig') }}
{% endblock %}